In [51]:

#!/usr/bin/python


#This script analyzes court of appeals decisions to predict whether, if a litigant in the case petitions the Supreme Court of the United States (SCOTUS) to hear the case, whether SCOTUS will grant a hearing or not. T
#Usage: python ~/Location_of_script/SCOTUS_analysis_final.py

#This script takes in a dataframe 
import sqlite3
from bs4 import BeautifulSoup
import re
import sys
import math
import os
import optparse
import json
import time
import matplotlib.pylab as plt
import requests
import pandas as pandas
import numpy
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn import metrics
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
import scipy

import sklearn
import pickle
import random
import math
import seaborn
import statistics
import nltk
df=pandas.read_table("/Users/joshuabroyde/Projects/Law_School_rankings/Law_school_rankings_input.txt")
df

                               School Name  Lieter  US-News
0                          Yale University       1        1
1                                  Harvard       2        3
2                    University of Chicago       3        4
3                      New York University       4        6
4                      Stanford University       5        2
5                      Columbia University       6        5
6      University of California (Berkeley)       7       12
7               University of Pennsylvania       8        7
8                   University of Virginia       9        8
9                   University of Michigan      10        8
10                         Duke University      11       10
11                 Northwestern University      12       10
12                   Georgetown University      13       15
13                      Cornell University      14       13
14  University of California (Los Angeles)      15       15
15            University of Texas (Austin)      16       14
16                   Vanderbilt University      17       17
17       University of Southern California      18       19
18            George Washington University      19       30
19       University of California (Irvine)      20       28
20                 University of Minnesota      21       23
21                       Boston University      22       26
22                        Emory University      23       22
23       Washington University (St. Louis)      24       18
24                      Fordham University      25       36
25                University of Notre Dame      26       20
26        University of California (Davis)      27       39
27                          Boston College      28       26
28                College of Wiliam & Mary      29       41
29                     Brooklyn Law School      30       88
30                 University of San Diego      31       77
31                       Cardozo Law Schoo      32       65
32                  University of Illinois      33       44
33                   Ohio State University      34       30
34            University of North Carolina      35       39
35        Indiana University (Bloomington)      36       30
36     University of California (Hastings)      37       54
37                      University of Iowa      38       20
38                Florida State University      39       48
39                 George Mason University      40       41

In [50]:
seaborn.set(font_scale=1)
ax=seaborn.lmplot(x ='Lieter', y = 'US-News',data=df,fit_reg=False)
ax.set(xlabel='Lieter Ranking', ylabel='US News Ranking')
seaborn.set(font_scale=1)
plt.xticks([1,10,20,30,40])
plt.yticks([1,10,20,30,40,50,60,70,80])
#plt.show()
plt.savefig('Law_School_Rankings.pdf')

Now get the correlaiton

In [44]:
scipy.stats.pearsonr(df["Lieter"],df["US-News"])

(0.7645246962797263, 9.3598957950041242e-09)